# Generated by Django 2.2 on 2020-10-10 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.IntegerField(choices=[(0, 'INACTIVE'), (1, 'ACTIVE')], default=1)),
                ('project_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.Project')),
            ],
            options={
                'db_table': 'staff_users',
            },
        ),
    ]
